import { Button } from '@/components/ui/button';
import { Printer, X } from 'lucide-react';

const fmt = (n) => `₱${Number(n || 0).toLocaleString('en-PH', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;

const Line = ({ label, value, strong }) => (
  <div className="flex items-center justify-between border-b border-slate-200 px-3 py-2 text-xs">
    <span className="text-slate-600">{label}</span>
    <span className={`tabular-nums ${strong ? 'font-bold text-slate-900' : 'font-medium text-slate-800'}`}>{value}</span>
  </div>
);

export default function Certificate2316({ employee, year, branch, onClose }) {
  return (
    <div className="fixed inset-0 z-[60] bg-black/50 flex items-center justify-center p-4">
      <div className="bg-white rounded-xl shadow-2xl w-full max-w-2xl max-h-[92vh] overflow-y-auto">
        <div id="certificate-content" className="p-7">
          <div className="text-center border-b-2 border-slate-800 pb-3 mb-4">
            <p className="text-xs text-slate-500">BIR Form No. 2316</p>
            <h2 className="text-base font-bold text-slate-900 uppercase">Certificate of Compensation Payment / Tax Withheld</h2>
            <p className="text-xs text-slate-600 mt-1">For the Year {year}{branch ? ` · ${branch}` : ''}</p>
          </div>

          <div className="grid grid-cols-2 gap-3 mb-4 text-xs">
            <div className="border border-slate-300 rounded p-3">
              <p className="text-slate-500">Employee Name</p>
              <p className="font-semibold text-slate-900 uppercase">{employee.employee_name}</p>
            </div>
            <div className="border border-slate-300 rounded p-3">
              <p className="text-slate-500">Employee Code</p>
              <p className="font-semibold text-slate-900">{employee.employee_code || '—'}</p>
            </div>
          </div>

          <div className="border border-slate-300 rounded-lg overflow-hidden">
            <div className="bg-slate-800 text-white px-3 py-2 text-xs font-bold uppercase tracking-wide">Compensation</div>
            <Line label="Gross Compensation Income" value={fmt(employee.gross)} />
            <div className="bg-slate-800 text-white px-3 py-2 text-xs font-bold uppercase tracking-wide">Non-Taxable Deductions</div>
            <Line label="SSS Contribution" value={fmt(employee.sss)} />
            <Line label="PhilHealth Contribution" value={fmt(employee.philhealth)} />
            <Line label="Pag-IBIG Contribution" value={fmt(employee.pagibig)} />
            <Line label="Total Contributions" value={fmt(employee.total_contributions)} strong />
            <div className="bg-slate-800 text-white px-3 py-2 text-xs font-bold uppercase tracking-wide">Tax Computation</div>
            <Line label="Taxable Compensation Income" value={fmt(employee.taxable_income)} />
            <Line label="Tax Due (Annual)" value={fmt(employee.annual_tax_due)} />
            <Line label="Tax Withheld" value={fmt(employee.tax_withheld)} strong />
          </div>

          <div className={`mt-4 rounded-lg px-4 py-3 flex items-center justify-between ${employee.adjustment > 0 ? 'bg-red-50 border border-red-200' : 'bg-green-50 border border-green-200'}`}>
            <span className="text-xs font-bold uppercase tracking-wide text-slate-700">
              {employee.adjustment > 0 ? 'Tax Still Due' : employee.adjustment < 0 ? 'Tax Refund' : 'Balanced'}
            </span>
            <span className={`text-lg font-bold tabular-nums ${employee.adjustment > 0 ? 'text-red-600' : 'text-green-600'}`}>
              {fmt(Math.abs(employee.adjustment))}
            </span>
          </div>

          <p className="text-[10px] text-slate-400 mt-4 italic text-center">
            Generated by PaySync PH from payroll records. Figures are estimates for internal review and must be validated against official BIR computations.
          </p>
        </div>

        <div className="flex gap-2 p-4 border-t print:hidden">
          <Button variant="outline" className="flex-1" onClick={onClose}><X className="w-4 h-4 mr-1.5" /> Close</Button>
          <Button className="flex-1" onClick={() => window.print()}><Printer className="w-4 h-4 mr-1.5" /> Print</Button>
        </div>
      </div>
    </div>
  );
}